version: '3.8'

services:
  # --- DATABASE ---
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: fashion_db
    restart: always  
    environment:
      SA_PASSWORD: "P@ssword_123" 
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  # --- RABBITMQ ---
  rabbitmq:
    image: rabbitmq:3-management
    container_name: fashion_rabbitmq
    restart: always
    ports:
      - "5672:5672"   
      - "15672:15672" 
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin"

  # --- BACKEND ---
  backend:
    build:
      context: ./backend/FashionStoreSystem
      dockerfile: FashionStore.WebAPI/Dockerfile
    container_name: fashion_backend
    restart: always
    ports:
      - "5000:80"
    depends_on:
      - db
      - rabbitmq
    environment:
      ASPNETCORE_HTTP_PORTS: "80"
      ConnectionStrings__DefaultConnection: "Server=db;Database=FashionStoreDb;User Id=sa;Password=P@ssword_123;TrustServerCertificate=True;"
      RabbitMQ__HostName: "rabbitmq"
      RabbitMQ__UserName: "admin" 
      RabbitMQ__Password: "admin"

  # --- FRONTEND ---
  frontend:
    build:
      context: ./frontend/fashion-store
      dockerfile: Dockerfile
    container_name: fashion_frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  sql_data: